# Generated by Django 3.1.2 on 2020-12-15 05:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_cart_txn_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='snack_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='emp_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='ind_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='snack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.snacks'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_time',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
